// milan-safety/data.js
// Official public data configuration only. The app does not create generated incident rows.

const translationDictionary = {
  en: {
    appTitle: "Milan Safety Map",
    appSubtitle: "Official annual reported-offence aggregates from Comune di Milano open data",
    viewMode: "Map Scope",
    heatmap: "City Total",
    bubbleMap: "Source Scope",
    choroplethMap: "Data Coverage",
    markerPins: "No Incident Pins",
    filterTitle: "Inspect Official Data",
    categoryLabel: "Crime type",
    allCategories: "All Crime Types",
    severityLabel: "Granularity",
    allSeverities: "Annual city aggregate",
    low: "Street level not available",
    medium: "Hour level not available",
    high: "Incident pins not available",
    timeLabel: "Hour filter is not available in this official annual source",
    allTimes: "No hour field",
    analyticsTitle: "Official Data Dashboard",
    totalIncidents: "Reported offences",
    districtRiskIndex: "Official annual count",
    noData: "No official records match the active filters.",
    legendTitle: "Official Data Scope",
    lowRiskDesc: "Comune di Milano annual aggregate",
    medRiskDesc: "Counts by year and crime type",
    highRiskDesc: "No street, hour, district, or incident coordinates",
    feedTitle: "Official Records",
    feedPlaceholder: "Search crime type, year, or count...",
    newsTickerTitle: "OFFICIAL DATA NOTICE",
    provenanceTitle: "Official Data Provenance",
    provenanceDesc: "Loaded from Comune di Milano DS564: reported offences to the judicial authority by police forces, 2004-2023. This source is annual and city-level.",
    citesLabel: "Official Citations:",
    dataViewTitle: "Data View",
    byHour: "Hour N/A",
    byDayOfMonth: "Day N/A",
    byMonthOfYear: "Month N/A",
    exactMonth: "Year",
    exactMonthLabel: "Official year",
    allMonths: "All Years",
    sourceOpen: "Open source",
    sourceMethod: "Source method",
    sourceRecord: "Official aggregate record",
    dataRecordsLabel: "records",
    filteredRecordsLabel: "filtered",
    sourceLinksLabel: "source links",
    yearLabel: "Year",
    countLabel: "Count",
    fieldLabel: "Official fields",
    unavailableLabel: "Unavailable in source",
    loadingData: "Loading official data...",
    loadFailed: "Official data could not be loaded",
    retrySource: "Open the official source URL",
    annualTrendTitle: "Annual Trend",
    crimeTypeTitle: "Crime Type Breakdown",
    overallTopTitle: "Top Crime Types Overall",
    unavailableChartTitle: "Requested Time Dimension Not In Source",
    sourceScopeTitle: "Source Coverage and Fields",
    exactYearTitle: "Selected Year Breakdown",
    experimentalNotice: "Experimental visualization only. No legal, safety, travel, policing, insurance, or public-policy advice.",
    urlLabel: "URL",
    licenseLabel: "License",
    updatedLabel: "Updated",
    scopeLabel: "Scope"
  },
  zh: {
    appTitle: "米兰安全地图",
    appSubtitle: "基于米兰市政府开放数据的年度报案聚合数据",
    viewMode: "地图范围",
    heatmap: "全市总量",
    bubbleMap: "来源范围",
    choroplethMap: "数据覆盖",
    markerPins: "无案件点位",
    filterTitle: "查看官方数据",
    categoryLabel: "犯罪类型",
    allCategories: "全部类型",
    severityLabel: "数据粒度",
    allSeverities: "年度全市聚合",
    low: "无街道级数据",
    medium: "无小时级数据",
    high: "无案件点位",
    timeLabel: "该官方年度数据源不提供小时筛选",
    allTimes: "无小时字段",
    analyticsTitle: "官方数据看板",
    totalIncidents: "报案数量",
    districtRiskIndex: "官方年度数量",
    noData: "当前筛选没有匹配的官方记录。",
    legendTitle: "官方数据范围",
    lowRiskDesc: "米兰市年度聚合数据",
    medRiskDesc: "按年份和犯罪类型统计",
    highRiskDesc: "不含街道、小时、区县或案件坐标",
    feedTitle: "官方记录",
    feedPlaceholder: "搜索犯罪类型、年份或数量...",
    newsTickerTitle: "官方数据说明",
    provenanceTitle: "官方数据来源",
    provenanceDesc: "数据加载自米兰市政府 DS564：警方上报司法机关的犯罪报案统计，覆盖 2004-2023 年。该来源为年度、全市级聚合。",
    citesLabel: "官方引用：",
    dataViewTitle: "数据视图",
    byHour: "小时无",
    byDayOfMonth: "日内无",
    byMonthOfYear: "月份无",
    exactMonth: "年份",
    exactMonthLabel: "官方年份",
    allMonths: "全部年份",
    sourceOpen: "打开来源",
    sourceMethod: "来源方法",
    sourceRecord: "官方聚合记录",
    dataRecordsLabel: "条记录",
    filteredRecordsLabel: "已筛选",
    sourceLinksLabel: "个来源链接",
    yearLabel: "年份",
    countLabel: "数量",
    fieldLabel: "官方字段",
    unavailableLabel: "来源不提供",
    loadingData: "正在加载官方数据...",
    loadFailed: "官方数据无法加载",
    retrySource: "打开官方来源 URL",
    annualTrendTitle: "年度趋势",
    crimeTypeTitle: "犯罪类型分布",
    overallTopTitle: "总体高频类型",
    unavailableChartTitle: "该时间维度不在官方来源中",
    sourceScopeTitle: "来源覆盖和字段",
    exactYearTitle: "所选年份分布",
    experimentalNotice: "实验性可视化；不构成法律、安全、旅行、执法、保险或公共政策建议。",
    urlLabel: "链接",
    licenseLabel: "许可",
    updatedLabel: "更新",
    scopeLabel: "范围"
  },
  it: {
    appTitle: "Mappa Sicurezza Milano",
    appSubtitle: "Dati annuali aggregati sui reati denunciati dal portale open data del Comune di Milano",
    viewMode: "Ambito Mappa",
    heatmap: "Totale Citta",
    bubbleMap: "Ambito Fonte",
    choroplethMap: "Copertura Dati",
    markerPins: "Nessun Pin",
    filterTitle: "Ispeziona Dati Ufficiali",
    categoryLabel: "Tipologia di reato",
    allCategories: "Tutte le tipologie",
    severityLabel: "Granularita",
    allSeverities: "Aggregato annuale comunale",
    low: "Livello strada non disponibile",
    medium: "Livello ora non disponibile",
    high: "Pin evento non disponibili",
    timeLabel: "Il filtro orario non e disponibile in questa fonte annuale",
    allTimes: "Nessun campo ora",
    analyticsTitle: "Dashboard Dati Ufficiali",
    totalIncidents: "Reati denunciati",
    districtRiskIndex: "Conteggio annuale ufficiale",
    noData: "Nessun record ufficiale corrisponde ai filtri attivi.",
    legendTitle: "Ambito Dati Ufficiali",
    lowRiskDesc: "Aggregato annuale Comune di Milano",
    medRiskDesc: "Conteggi per anno e tipologia",
    highRiskDesc: "Nessuna strada, ora, zona o coordinata evento",
    feedTitle: "Record Ufficiali",
    feedPlaceholder: "Cerca tipologia, anno o conteggio...",
    newsTickerTitle: "NOTA DATI UFFICIALI",
    provenanceTitle: "Provenienza Dati Ufficiali",
    provenanceDesc: "Dati caricati dal dataset DS564 del Comune di Milano: reati denunciati all'autorita giudiziaria dalle forze di polizia, 2004-2023. La fonte e annuale e comunale.",
    citesLabel: "Citazioni ufficiali:",
    dataViewTitle: "Vista Dati",
    byHour: "Ora N/D",
    byDayOfMonth: "Giorno N/D",
    byMonthOfYear: "Mese N/D",
    exactMonth: "Anno",
    exactMonthLabel: "Anno ufficiale",
    allMonths: "Tutti gli anni",
    sourceOpen: "Apri fonte",
    sourceMethod: "Metodo fonte",
    sourceRecord: "Record aggregato ufficiale",
    dataRecordsLabel: "record",
    filteredRecordsLabel: "filtrati",
    sourceLinksLabel: "link fonte",
    yearLabel: "Anno",
    countLabel: "Conteggio",
    fieldLabel: "Campi ufficiali",
    unavailableLabel: "Non disponibile nella fonte",
    loadingData: "Caricamento dati ufficiali...",
    loadFailed: "Impossibile caricare i dati ufficiali",
    retrySource: "Apri URL della fonte ufficiale",
    annualTrendTitle: "Trend Annuale",
    crimeTypeTitle: "Ripartizione per Tipologia",
    overallTopTitle: "Tipologie Principali",
    unavailableChartTitle: "Dimensione temporale non presente nella fonte",
    sourceScopeTitle: "Copertura e Campi Fonte",
    exactYearTitle: "Ripartizione Anno Selezionato",
    experimentalNotice: "Visualizzazione sperimentale: non e consulenza legale, sicurezza, viaggio, polizia, assicurazione o policy.",
    urlLabel: "URL",
    licenseLabel: "Licenza",
    updatedLabel: "Aggiornato",
    scopeLabel: "Ambito"
  }
};

const officialCrimeDataset = {
  id: "comune-milano-ds564",
  resourceId: "8b03b9f2-f2d7-4408-b439-bc6efc093cff",
  name: "Reati denunciati all'autorita giudiziaria dalla forze di polizia (2004 - 2023)",
  publisher: "Comune di Milano",
  landingPage: "https://dati.comune.milano.it/dataset/ds564-reati-denunciati-all-autorita-giudiziaria-dalla-forze-di-polizia-2004-avanti",
  resourcePage: "https://dati.comune.milano.it/dataset/ds564-reati-denunciati-all-autorita-giudiziaria-dalla-forze-di-polizia-2004-avanti/resource/8b03b9f2-f2d7-4408-b439-bc6efc093cff",
  apiUrl: "https://dati.comune.milano.it/api/3/action/datastore_search?resource_id=8b03b9f2-f2d7-4408-b439-bc6efc093cff&limit=5000",
  csvUrl: "https://dati.comune.milano.it/dataset/34e2d2af-5c3b-4768-918b-ab7e5c0d15da/resource/8b03b9f2-f2d7-4408-b439-bc6efc093cff/download/ds564_reati_denunciati_2004_2023.csv",
  jsonUrl: "https://dati.comune.milano.it/dataset/34e2d2af-5c3b-4768-918b-ab7e5c0d15da/resource/3227db9d-8802-4b00-b237-0618380dab1d/download/ds564_reati_denunciati_2004_2023.json",
  license: "Creative Commons Attribution 4.0 International (CC BY 4.0)",
  temporalCoverage: "2004-01-01 to 2023-12-31",
  lastUpdated: "2026-05-08 12:29 CEST",
  geographicCoverage: "Comune di Milano",
  granularity: "annual city-level aggregate by crime type",
  fields: [
    { name: "anno_rilevamento_reato", type: "numeric", description: "Year the offence was recorded" },
    { name: "Reati_denunciati_tipologia", type: "text", description: "Reported-offence type" },
    { name: "reati_denunciati", type: "text", description: "Reported-offence count" }
  ],
  unavailableDimensions: [
    "hour",
    "day of month",
    "month of year",
    "exact month",
    "street address",
    "district",
    "incident coordinates",
    "real-time alerts"
  ]
};

const officialDataSources = [
  {
    id: "comune-milano-ds564",
    name: "Comune di Milano DS564",
    type: "official open data landing page",
    url: officialCrimeDataset.landingPage,
    usedFor: "Metadata, publisher, description, temporal coverage, and license",
    cadence: "Annual"
  },
  {
    id: "comune-milano-api",
    name: "CKAN Data API",
    type: "official runtime API",
    url: officialCrimeDataset.apiUrl,
    usedFor: "Records loaded by this prototype",
    cadence: "Annual"
  },
  {
    id: "comune-milano-csv",
    name: "Official CSV",
    type: "official data file",
    url: officialCrimeDataset.csvUrl,
    usedFor: "Downloadable source file and data dictionary",
    cadence: "Annual"
  },
  {
    id: "comune-milano-json",
    name: "Official JSON",
    type: "official data file",
    url: officialCrimeDataset.jsonUrl,
    usedFor: "Alternative downloadable JSON source file",
    cadence: "Annual"
  },
  {
    id: "milanostatistica",
    name: "Milano Statistica",
    type: "official source path",
    url: "https://milanostatistica.comune.milano.it/",
    usedFor: "Original source path cited by the Comune di Milano dataset",
    cadence: "Annual"
  },
  {
    id: "openstreetmap",
    name: "OpenStreetMap",
    type: "map base",
    url: "https://www.openstreetmap.org/copyright",
    usedFor: "Basemap geometry and attribution",
    cadence: "Community-updated basemap"
  },
  {
    id: "carto-basemap",
    name: "CARTO Basemap",
    type: "map style",
    url: "https://carto.com/attributions",
    usedFor: "Dark basemap rendering",
    cadence: "Basemap attribution"
  }
];

const milanOfficialArea = {
  id: "comune-milano",
  nameEn: "Comune di Milano",
  nameZh: "米兰市",
  nameIt: "Comune di Milano",
  lat: 45.4642,
  lng: 9.19
};

const recentNewsAlerts = [
  {
    en: "Official data mode: records load from Comune di Milano DS564. The app does not create generated incident rows.",
    zh: "官方数据模式：记录来自米兰市政府 DS564，本应用不生成案件行。",
    it: "Modalita dati ufficiali: i record arrivano dal DS564 del Comune di Milano; l'app non genera righe evento."
  },
  {
    en: "Public source granularity is annual and city-level; hour, day, month, street, district, and exact coordinates are not in DS564.",
    zh: "该公开来源为年度、全市级聚合；DS564 不包含小时、日期、月份、街道、区县或精确坐标。",
    it: "La fonte pubblica e annuale e comunale; DS564 non include ora, giorno, mese, strada, zona o coordinate esatte."
  },
  {
    en: "Experimental visualization only. Do not use for legal, safety, travel, policing, insurance, housing, or public-policy decisions.",
    zh: "仅为实验性可视化；请勿用于法律、安全、旅行、执法、保险、住房或公共政策决策。",
    it: "Solo visualizzazione sperimentale. Non usare per decisioni legali, sicurezza, viaggio, polizia, assicurazione, casa o policy."
  }
];
