// SPDX-License-Identifier: AGPL-3.0-or-later
// Real GDELT GKG news-document snapshot generated from public export CSV files.
window.milanNewsSnapshot = {
    "generatedAt":  "2026-06-09T20:34:49.9724245Z",
    "source":  {
                   "name":  "GDELT 2.1 Global Knowledge Graph GKG CSV",
                   "masterFileList":  "http://data.gdeltproject.org/gdeltv2/masterfilelist.txt",
                   "docs":  "https://www.gdeltproject.org/data.html",
                   "note":  "Real GDELT GKG news-document records filtered for Milan/Milano location mentions; safety/crime themes or URL terms are prioritized. Location coordinates are processed from place keywords or GDELT Milan location mentions, not official incident coordinates."
               },
    "requested":  {
                      "year2026":  20,
                      "year2025":  40
                  },
    "received":  {
                     "year2026":  20,
                     "year2025":  40
                 },
    "items":  [
                  {
                      "id":  "gdelt-gkg-20260605060000-179",
                      "year":  2026,
                      "date":  "2026-06-05",
                      "dateAdded":  "20260605060000",
                      "title":  "Article 788Ca333 5985 5818 855F 23Bc777e40c0",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.smdailyjournal.com/arts_and_entertainment/ap-entertainment-summarybrief-at-12-03-a-m-edt/article_788ca333-5985-5818-855f-23bc777e40c0.html",
                      "domain":  "smdailyjournal.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20260605060000-179",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260605060000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "TAX_FNCACT_KILLER",
                                          "KILL",
                                          "CRIME_ILLEGAL_DRUGS",
                                          "DRUG_TRADE",
                                          "TAX_FNCACT_JUDGE",
                                          "TAX_FNCACT_JUDGE,3614",
                                          "TAX_FNCACT_JUDGE,3774",
                                          "TAX_FNCACT_JUDGE,4080"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260605000000-692",
                      "year":  2026,
                      "date":  "2026-06-05",
                      "dateAdded":  "20260605000000",
                      "title":  "Venice Biennale Artists Demand Names Removed From Visitors Ballot And Threaten Lawsuit",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://medicinehatnews.com/entertainment/entertainment-news/2026/06/04/venice-biennale-artists-demand-names-removed-from-visitors-ballot-and-threaten-lawsuit/",
                      "domain":  "medicinehatnews.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20260605000000-692",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260605000000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE",
                                          "WB_2433_CONFLICT_AND_VIOLENCE",
                                          "WB_2462_POLITICAL_VIOLENCE_AND_WAR",
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE,2240",
                                          "WB_2433_CONFLICT_AND_VIOLENCE,2252",
                                          "WB_2462_POLITICAL_VIOLENCE_AND_WAR,2252"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260604160000-1644",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604160000",
                      "title":  "hospitalitydesign.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://hospitalitydesign.com/projects/brand-identity-delano-hotels-ennismore/629411",
                      "domain":  "hospitalitydesign.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "publicOrder",
                      "gdeltRecordId":  "20260604160000-1644",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604160000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "SOC_GENERALCRIME",
                                          "SOC_GENERALCRIME,1338"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260603200000-553",
                      "year":  2026,
                      "date":  "2026-06-03",
                      "dateAdded":  "20260603200000",
                      "title":  "www.miragenews.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.miragenews.com/real-world-evidence-in-rheumatology-1685939/",
                      "domain":  "miragenews.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20260603200000-553",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260603200000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "UNGP_CRIME_VIOLENCE",
                                          "CRISISLEX_C07_SAFETY",
                                          "WB_2433_CONFLICT_AND_VIOLENCE",
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE",
                                          "WB_2456_DRUGS_AND_NARCOTICS",
                                          "CRISISLEX_C07_SAFETY,3788",
                                          "WB_2433_CONFLICT_AND_VIOLENCE,8245",
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE,8245"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260602160000-1481",
                      "year":  2026,
                      "date":  "2026-06-02",
                      "dateAdded":  "20260602160000",
                      "title":  "Indian National Lubana Singh Added To Dhs Worst Of The Worst List As Us Expands Migrant Crime Database Article 13938973",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.moneycontrol.com/world/indian-national-lubana-singh-added-to-dhs-worst-of-the-worst-list-as-us-expands-migrant-crime-database-article-13938973.html",
                      "domain":  "moneycontrol.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "robbery",
                      "gdeltRecordId":  "20260602160000-1481",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260602160000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "CRISISLEX_C07_SAFETY",
                                          "ARREST",
                                          "SOC_GENERALCRIME",
                                          "CRIME_ILLEGAL_DRUGS",
                                          "DRUG_TRADE",
                                          "WB_2433_CONFLICT_AND_VIOLENCE",
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE",
                                          "WB_2456_DRUGS_AND_NARCOTICS"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260602080000-722",
                      "year":  2026,
                      "date":  "2026-06-02",
                      "dateAdded":  "20260602080000",
                      "title":  "Weather Any Storm Student Designer",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://stanforddaily.com/2026/06/01/weather-any-storm-student-designer/",
                      "domain":  "stanforddaily.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20260602080000-722",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260602080000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,2574",
                                          "KILL,2996"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260602000000-647",
                      "year":  2026,
                      "date":  "2026-06-02",
                      "dateAdded":  "20260602000000",
                      "title":  "Man Charged Fatal Omaha Stabbing Changes Plea",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.wowt.com/2026/06/01/man-charged-fatal-omaha-stabbing-changes-plea/",
                      "domain":  "wowt.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20260602000000-647",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260602000000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "ARREST",
                                          "SOC_GENERALCRIME",
                                          "CRISISLEX_C07_SAFETY",
                                          "ARREST,36",
                                          "SOC_GENERALCRIME,36",
                                          "CRISISLEX_C07_SAFETY,36"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260601160000-988",
                      "year":  2026,
                      "date":  "2026-06-01",
                      "dateAdded":  "20260601160000",
                      "title":  "India Australia To Inaugurate Joint Staff Talks Reaffirm Commitment To Quad Initiatives",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "http://www.bignewsnetwork.com/news/279095325/india-australia-to-inaugurate-joint-staff-talks-reaffirm-commitment-to-quad-initiatives",
                      "domain":  "bignewsnetwork.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "weapons",
                      "gdeltRecordId":  "20260601160000-988",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260601160000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "TAX_WEAPONS",
                                          "TAX_WEAPONS_SUBMARINE",
                                          "TAX_WEAPONS_SUBMARINE,1921"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20260605060000-248",
                      "year":  2026,
                      "date":  "2026-06-05",
                      "dateAdded":  "20260605060000",
                      "title":  "www.el-balad.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.el-balad.com/17017288",
                      "domain":  "el-balad.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260605060000-248",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260605060000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260605040000-416",
                      "year":  2026,
                      "date":  "2026-06-05",
                      "dateAdded":  "20260605040000",
                      "title":  "news.tuoitre.vn",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://news.tuoitre.vn/la28-to-study-los-angeles-world-cup-matches-as-olympic-test-case-ceo-says-103260605102009897.htm",
                      "domain":  "news.tuoitre.vn",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260605040000-416",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260605040000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260605020000-1011",
                      "year":  2026,
                      "date":  "2026-06-05",
                      "dateAdded":  "20260605020000",
                      "title":  "wildcatbluenation.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://wildcatbluenation.com/national-analyst-forecasts-milan-momcilovic-s-domination-in-a-top-10-list-01ktac5pjqyc",
                      "domain":  "wildcatbluenation.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260605020000-1011",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260605020000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260605000000-718",
                      "year":  2026,
                      "date":  "2026-06-05",
                      "dateAdded":  "20260605000000",
                      "title":  "Shakira Discovered How Resilient We All Are Following Ex Gerard Piques Alleged Affair",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://nbcmontana.com/news/entertainment/shakira-discovered-how-resilient-we-all-are-following-ex-gerard-piques-alleged-affair",
                      "domain":  "nbcmontana.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260605000000-718",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260605000000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604220000-524",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604220000",
                      "title":  "Shakira Discovered How Resilient We All Are Following Ex Gerard Piques Alleged Affair",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://wjla.com/news/entertainment/shakira-discovered-how-resilient-we-all-are-following-ex-gerard-piques-alleged-affair",
                      "domain":  "wjla.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260604220000-524",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604220000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604220000-476",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604220000",
                      "title":  "Shakira Discovered How Resilient We All Are Following Ex Gerard Piques Alleged Affair",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://cbs6albany.com/news/entertainment/shakira-discovered-how-resilient-we-all-are-following-ex-gerard-piques-alleged-affair",
                      "domain":  "cbs6albany.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260604220000-476",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604220000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604220000-293",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604220000",
                      "title":  "Shakira Discovered How Resilient We All Are Following Ex Gerard Piques Alleged Affair",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://fox42kptm.com/news/entertainment/shakira-discovered-how-resilient-we-all-are-following-ex-gerard-piques-alleged-affair",
                      "domain":  "fox42kptm.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260604220000-293",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604220000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604220000-1287",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604220000",
                      "title":  "Shakira Discovered How Resilient We All Are Following Ex Gerard Piques Alleged Affair",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://abc6onyourside.com/news/entertainment/shakira-discovered-how-resilient-we-all-are-following-ex-gerard-piques-alleged-affair",
                      "domain":  "abc6onyourside.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260604220000-1287",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604220000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604220000-1200",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604220000",
                      "title":  "Shakira Discovered How Resilient We All Are Following Ex Gerard Piques Alleged Affair",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://wgme.com/news/entertainment/shakira-discovered-how-resilient-we-all-are-following-ex-gerard-piques-alleged-affair",
                      "domain":  "wgme.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260604220000-1200",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604220000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604220000-770",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604220000",
                      "title":  "World Cup Opening Ceremonies",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.dailyfreeman.com/2026/06/04/world-cup-opening-ceremonies/",
                      "domain":  "dailyfreeman.com",
                      "locationName":  "San Siro",
                      "lat":  45.478,
                      "lng":  9.123,
                      "confidence":  "place-keyword",
                      "category":  "other",
                      "gdeltRecordId":  "20260604220000-770",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604220000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604200000-579",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604200000",
                      "title":  "World Cup Opening Ceremonies",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.oneidadispatch.com/2026/06/04/world-cup-opening-ceremonies/",
                      "domain":  "oneidadispatch.com",
                      "locationName":  "San Siro",
                      "lat":  45.478,
                      "lng":  9.123,
                      "confidence":  "place-keyword",
                      "category":  "other",
                      "gdeltRecordId":  "20260604200000-579",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604200000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20260604180000-230",
                      "year":  2026,
                      "date":  "2026-06-04",
                      "dateAdded":  "20260604180000",
                      "title":  "World Cup Opening Ceremonies Us Canada Mexico Unity",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.eastbaytimes.com/2026/06/04/world-cup-opening-ceremonies-us-canada-mexico-unity/",
                      "domain":  "eastbaytimes.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20260604180000-230",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20260604180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-221",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "Public Viewing For Pope Francis Begins Wednesday Ahead Of Saturday Funeral",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.wbaa.org/2025-04-22/public-viewing-for-pope-francis-begins-wednesday-ahead-of-saturday-funeral",
                      "domain":  "wbaa.org",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250422120000-221",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,619"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-872",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "Public Viewing For Pope Francis Begins Wednesday Ahead Of Saturday Funeral",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://kansaspublicradio.org/npr-news/2025-04-22/public-viewing-for-pope-francis-begins-wednesday-ahead-of-saturday-funeral",
                      "domain":  "kansaspublicradio.org",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250422120000-872",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,619"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-1113",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "Public Viewing For Pope Francis Begins Wednesday Ahead Of Saturday Funeral",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.wclk.com/2025-04-22/public-viewing-for-pope-francis-begins-wednesday-ahead-of-saturday-funeral",
                      "domain":  "wclk.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250422120000-1113",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,619"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250422060000-107",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422060000",
                      "title":  "blueprint.ng",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://blueprint.ng/tinubu-other-world-leaders-mourn-as-ghanaian-cardinal-9-others-in-line-to-replace-pope-francis/",
                      "domain":  "blueprint.ng",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250422060000-107",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422060000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,3945",
                                          "KILL,6046"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250415120000-1433",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415120000",
                      "title":  "www.womenofchina.cn",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.womenofchina.cn/womenofchina/html1/In-depth/Features/2504/1039-1.htm",
                      "domain":  "womenofchina.cn",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "publicOrder",
                      "gdeltRecordId":  "20250415120000-1433",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415120000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "CRISISLEX_C07_SAFETY",
                                          "CRISISLEX_C07_SAFETY,1700"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250401180000-1099",
                      "year":  2025,
                      "date":  "2025-04-01",
                      "dateAdded":  "20250401180000",
                      "title":  "Photos Caravaggio 2025 Baroque Masters Works On Display As Part Of Jubilee Of Hope",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.catholicnewsagency.com/news/263095/photos-caravaggio-2025-baroque-masters-works-on-display-as-part-of-jubilee-of-hope",
                      "domain":  "catholicnewsagency.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250401180000-1099",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250401180000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "HUMAN_TRAFFICKING",
                                          "SOC_GENERALCRIME",
                                          "SOC_GENERALCRIME,5992",
                                          "HUMAN_TRAFFICKING,4061"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250322180000-774",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322180000",
                      "title":  "Van Der Poel Benefits Pogacars 164412464",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.yahoo.com/news/van-der-poel-benefits-pogacars-164412464.html",
                      "domain":  "yahoo.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250322180000-774",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322180000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,970"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250322180000-941",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322180000",
                      "title":  "Van Der Poel Benefits From Pogacars Early Attack To Win Milan San Remo Again",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.mymotherlode.com/news/world/3675277/van-der-poel-benefits-from-pogacars-early-attack-to-win-milan-san-remo-again.html",
                      "domain":  "mymotherlode.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250322180000-941",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322180000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,1015"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250322120000-432",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322120000",
                      "title":  "151610 Switzerlands Lodyssey Axes Network To One Saab 2000 Route",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.ch-aviation.com/news/151610-switzerlands-lodyssey-axes-network-to-one-saab-2000-route",
                      "domain":  "ch-aviation.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250322120000-432",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322120000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "UNGP_CRIME_VIOLENCE",
                                          "UNGP_CRIME_VIOLENCE,980"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250301000000-1673",
                      "year":  2025,
                      "date":  "2025-03-01",
                      "dateAdded":  "20250301000000",
                      "title":  "Article Ad4e18e0 2711 5282 Aa1a 113E082fc103",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.bdtonline.com/news/entertainment/at-90-giorgio-armani-has-more-than-a-few-cards-up-his-sleeve-on-the/article_ad4e18e0-2711-5282-aa1a-113e082fc103.html",
                      "domain":  "bdtonline.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "weapons",
                      "gdeltRecordId":  "20250301000000-1673",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250301000000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250122180000-758",
                      "year":  2025,
                      "date":  "2025-01-22",
                      "dateAdded":  "20250122180000",
                      "title":  "Musks Straight Arm Gesture Embraced By Right Wing Extremists Regardless Of What He Meant",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://fox23maine.com/news/nation-world/musks-straight-arm-gesture-embraced-by-right-wing-extremists-regardless-of-what-he-meant",
                      "domain":  "fox23maine.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250122180000-758",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250122180000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "TERROR",
                                          "KILL",
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE",
                                          "UNGP_CRIME_VIOLENCE",
                                          "WB_2467_TERRORISM",
                                          "WB_2433_CONFLICT_AND_VIOLENCE",
                                          "WB_2462_POLITICAL_VIOLENCE_AND_WAR",
                                          "WB_2467_TERRORISM,2897"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250122120000-978",
                      "year":  2025,
                      "date":  "2025-01-22",
                      "dateAdded":  "20250122120000",
                      "title":  "News Turns Out Leonardo Da Vinci Was Right Secret Tunnels Found Beneath Italys Sforza Castle 22 01 2025",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://eng.obozrevatel.com/section-news/news-turns-out-leonardo-da-vinci-was-right-secret-tunnels-found-beneath-italys-sforza-castle-22-01-2025.html",
                      "domain":  "obozrevatel.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250122120000-978",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250122120000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "KILL,1180"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250122000000-1104",
                      "year":  2025,
                      "date":  "2025-01-22",
                      "dateAdded":  "20250122000000",
                      "title":  "www.brooklynvegan.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.brooklynvegan.com/tour-news-duran-duran-gillian-welch-david-rawlings-jamie-xx-khanate-between-the-buried-me-more/",
                      "domain":  "brooklynvegan.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250122000000-1104",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250122000000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KIDNAP",
                                          "KIDNAP,3070",
                                          "KIDNAP,3153",
                                          "KIDNAP,3351"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250122000000-1149",
                      "year":  2025,
                      "date":  "2025-01-22",
                      "dateAdded":  "20250122000000",
                      "title":  "Musks Straight Arm Gesture Embraced By Right Wing Extremists Regardless Of What He Meant",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.columbian.com/news/2025/jan/21/musks-straight-arm-gesture-embraced-by-right-wing-extremists-regardless-of-what-he-meant/",
                      "domain":  "columbian.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250122000000-1149",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250122000000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "TERROR",
                                          "KILL",
                                          "WB_2432_FRAGILITY_CONFLICT_AND_VIOLENCE",
                                          "UNGP_CRIME_VIOLENCE",
                                          "WB_2467_TERRORISM",
                                          "WB_2433_CONFLICT_AND_VIOLENCE",
                                          "WB_2462_POLITICAL_VIOLENCE_AND_WAR",
                                          "TERROR,57"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250108180000-197",
                      "year":  2025,
                      "date":  "2025-01-08",
                      "dateAdded":  "20250108180000",
                      "title":  "Wrong Carabinieri Involved In Fatal Chase Says Ramys Dad A4335986 8774 412C Bac5 38Dcca14ca05",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.ansa.it/english/news/2025/01/08/wrong-carabinieri-involved-in-fatal-chase-says-ramys-dad_a4335986-8774-412c-bac5-38dcca14ca05.html",
                      "domain":  "ansa.it",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250108180000-197",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250108180000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KILL",
                                          "TAX_FNCACT_POLICE",
                                          "CRISISLEX_C07_SAFETY",
                                          "TAX_FNCACT_POLICE,135",
                                          "CRISISLEX_C07_SAFETY,135",
                                          "KILL,54"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250108000000-529",
                      "year":  2025,
                      "date":  "2025-01-08",
                      "dateAdded":  "20250108000000",
                      "title":  "Home Sweet Home Americas First Hit Song 5499110",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.theepochtimes.com/bright/home-sweet-home-americas-first-hit-song-5499110",
                      "domain":  "theepochtimes.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250108000000-529",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250108000000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "WB_739_POLITICAL_VIOLENCE_AND_CIVIL_WAR",
                                          "WB_739_POLITICAL_VIOLENCE_AND_CIVIL_WAR,443",
                                          "WB_739_POLITICAL_VIOLENCE_AND_CIVIL_WAR,4802",
                                          "WB_739_POLITICAL_VIOLENCE_AND_CIVIL_WAR,5140",
                                          "WB_739_POLITICAL_VIOLENCE_AND_CIVIL_WAR,6579",
                                          "WB_739_POLITICAL_VIOLENCE_AND_CIVIL_WAR,7280"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250101060000-483",
                      "year":  2025,
                      "date":  "2025-01-01",
                      "dateAdded":  "20250101060000",
                      "title":  "Lara Trump Donald Elon Musk Mar Lago Tom Petty",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.dailymail.co.uk/news/article-14240813/Lara-Trump-Donald-Elon-Musk-Mar-Lago-tom-petty.html",
                      "domain":  "dailymail.co.uk",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250101060000-483",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250101060000.gkg.csv.zip",
                      "gdeltThemes":  [
                                          "KIDNAP",
                                          "KIDNAP,2644"
                                      ],
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250101000000-205",
                      "year":  2025,
                      "date":  "2025-01-01",
                      "dateAdded":  "20250101000000",
                      "title":  "The New Cars Coming To Australia In 2025 And Beyond",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.armidaleexpress.com.au/story/8857250/the-new-cars-coming-to-australia-in-2025-and-beyond/?cs=34616",
                      "domain":  "armidaleexpress.com.au",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "weapons",
                      "gdeltRecordId":  "20250101000000-205",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250101000000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "safety-theme-or-url-term"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-793",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "brudirect.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://brudirect.com/news.php?id=199293",
                      "domain":  "brudirect.com",
                      "locationName":  "San Siro",
                      "lat":  45.478,
                      "lng":  9.123,
                      "confidence":  "place-keyword",
                      "category":  "other",
                      "gdeltRecordId":  "20250422120000-793",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-304",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "Pope Francis Funeral 2",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.chicagotribune.com/2025/04/22/pope-francis-funeral-2/",
                      "domain":  "chicagotribune.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250422120000-304",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-1393",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "thechronicle.com.gh",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://thechronicle.com.gh/todays-european-leagues-fixtures-preview/",
                      "domain":  "thechronicle.com.gh",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250422120000-1393",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250422120000-1022",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422120000",
                      "title":  "www.localgov.co.uk",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.localgov.co.uk/Welsh-councils-in-need-of-net-zero-funding/62255",
                      "domain":  "localgov.co.uk",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250422120000-1022",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250422000000-980",
                      "year":  2025,
                      "date":  "2025-04-22",
                      "dateAdded":  "20250422000000",
                      "title":  "Pope Francis Dies",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.lowellsun.com/2025/04/21/pope-francis-dies/",
                      "domain":  "lowellsun.com",
                      "locationName":  "Porta Venezia",
                      "lat":  45.475,
                      "lng":  9.205,
                      "confidence":  "place-keyword",
                      "category":  "other",
                      "gdeltRecordId":  "20250422000000-980",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250422000000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415180000-876",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415180000",
                      "title":  "Beni Mellal Khenifra Where Atlas Mountains Guard Moroccos Hidden Paradise",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.moroccoworldnews.com/2025/04/190386/beni-mellal-khenifra-where-atlas-mountains-guard-moroccos-hidden-paradise/",
                      "domain":  "moroccoworldnews.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250415180000-876",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415120000-275",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415120000",
                      "title":  "borneobulletin.com.bn",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://borneobulletin.com.bn/mbappe-leading-real-madrid-comeback-charge-against-arsenal/",
                      "domain":  "borneobulletin.com.bn",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250415120000-275",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415120000-162",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415120000",
                      "title":  "Exclusive Newcastle United Move Complete Player",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.caughtoffside.com/2025/04/15/exclusive-newcastle-united-move-complete-player/",
                      "domain":  "caughtoffside.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250415120000-162",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415120000-1082",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415120000",
                      "title":  "borneobulletin.com.bn",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://borneobulletin.com.bn/kane-and-bayern-need-killer-instinct-with-home-final-at-stake/",
                      "domain":  "borneobulletin.com.bn",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "assault",
                      "gdeltRecordId":  "20250415120000-1082",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415120000-412",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415120000",
                      "title":  "Man United Plotting Summer Move Yahia Fofana",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.caughtoffside.com/2025/04/15/man-united-plotting-summer-move-yahia-fofana/",
                      "domain":  "caughtoffside.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250415120000-412",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415060000-49",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415060000",
                      "title":  "Article A45cca9d 76D5 56B4 91C1 37C9fad7730c",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.youralaskalink.com/news/national/mbappe-leading-real-madrid-comeback-charge-against-arsenal/article_a45cca9d-76d5-56b4-91c1-37c9fad7730c.html",
                      "domain":  "youralaskalink.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250415060000-49",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415060000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250415000000-215",
                      "year":  2025,
                      "date":  "2025-04-15",
                      "dateAdded":  "20250415000000",
                      "title":  "No 2 Iowa State Indefinitely Loses F Milan Momcilovic Hand",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.921theticket.com/news/no-2-iowa-state-indefinitely-loses-f-milan-momcilovic-hand/",
                      "domain":  "921theticket.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250415000000-215",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250415000000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250408180000-424",
                      "year":  2025,
                      "date":  "2025-04-08",
                      "dateAdded":  "20250408180000",
                      "title":  "120102967.Cms",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://economictimes.indiatimes.com/news/international/us/uefa-champions-league-2025-quarter-finals-live-streaming-starting-xi-and-injury-updates-for-arsenal-vs-real-madrid-bayern-vs-inter-milan/articleshow/120102967.cms",
                      "domain":  "indiatimes.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250408180000-424",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250408180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250401180000-1046",
                      "year":  2025,
                      "date":  "2025-04-01",
                      "dateAdded":  "20250401180000",
                      "title":  "Poliform Plans Opening Former Trussardis Space Milan 1237067135",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://wwd.com/home-design/furniture/poliform-plans-opening-former-trussardis-space-milan-1237067135/",
                      "domain":  "wwd.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250401180000-1046",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250401180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250401120000-1085",
                      "year":  2025,
                      "date":  "2025-04-01",
                      "dateAdded":  "20250401120000",
                      "title":  "www.topspeed.com",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.topspeed.com/mitsubishi-miland-virtual-car-world-generation-z/",
                      "domain":  "topspeed.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250401120000-1085",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250401120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250322180000-286",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322180000",
                      "title":  "Van Der Poel Pips Pogacar To Take Milan Sanremo Title",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.juneesoutherncross.com.au/story/8923527/van-der-poel-pips-pogacar-to-take-milan-sanremo-title/?cs=6409",
                      "domain":  "juneesoutherncross.com.au",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250322180000-286",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250322180000-806",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322180000",
                      "title":  "Van Der Poel Pips Pogacar To Take Milan Sanremo Title",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.juneesoutherncross.com.au/story/8923527/van-der-poel-pips-pogacar-to-take-milan-sanremo-title/?cs=6417",
                      "domain":  "juneesoutherncross.com.au",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250322180000-806",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250322180000-973",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322180000",
                      "title":  "Uefa Nations League Nagelsmann Calls Second Leg Against Italy 460",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.newkerala.com/news/o/uefa-nations-league-nagelsmann-calls-second-leg-against-italy-460",
                      "domain":  "newkerala.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250322180000-973",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250322060000-676",
                      "year":  2025,
                      "date":  "2025-03-22",
                      "dateAdded":  "20250322060000",
                      "title":  "Real Madrid Femenino Womens Champions League Spain",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.nytimes.com/athletic/6218688/2025/03/22/real-madrid-femenino-womens-champions-league-spain/",
                      "domain":  "nytimes.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250322060000-676",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250322060000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250315180000-600",
                      "year":  2025,
                      "date":  "2025-03-15",
                      "dateAdded":  "20250315180000",
                      "title":  "Manchester United Considering Lucas Chevalier Swoop",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://thehardtackle.com/transfer-news/2025/03/15/manchester-united-considering-lucas-chevalier-swoop/",
                      "domain":  "thehardtackle.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250315180000-600",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250315180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250315180000-650",
                      "year":  2025,
                      "date":  "2025-03-15",
                      "dateAdded":  "20250315180000",
                      "title":  "Fiorentina Vs Juventus Preview And Prediction",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://thehardtackle.com/round-up/2025/03/15/fiorentina-vs-juventus-preview-and-prediction/",
                      "domain":  "thehardtackle.com",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250315180000-650",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250315180000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  },
                  {
                      "id":  "gdelt-gkg-20250315120000-239",
                      "year":  2025,
                      "date":  "2025-03-15",
                      "dateAdded":  "20250315120000",
                      "title":  "A New Team And A New Attitude Lewis Hamilton Cruises Into The 2025 Formula 1 Season",
                      "titleMethod":  "source URL slug label; open source URL to inspect the article",
                      "url":  "https://www.kbia.org/2025-03-15/a-new-team-and-a-new-attitude-lewis-hamilton-cruises-into-the-2025-formula-1-season",
                      "domain":  "kbia.org",
                      "locationName":  "Milano Citywide",
                      "lat":  45.4642,
                      "lng":  9.19,
                      "confidence":  "gdelt-location-mention",
                      "category":  "other",
                      "gdeltRecordId":  "20250315120000-239",
                      "gdeltExportUrl":  "http://data.gdeltproject.org/gdeltv2/20250315120000.gkg.csv.zip",
                      "gdeltThemes":  {

                                      },
                      "dataTier":  "milan-location-mention"
                  }
              ]
}
;

